### ISSUE TITLE
Enhance error message when credential manager fails to initialize

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli-secrets-for-kubernetes#15]
Currently if the K8s `readNamespace` API fails, and the error code is not 401 or 403, we assume that "namespace does not exist" in the error message:
https://github.com/zowe/zowe-cli-secrets-for-kubernetes/blob/bd43346bddb54c2bb8550c9c31f187e582a4afc7/packages/cli/src/credentials/K8sCredentialManager.ts#L65-L67

This message can be misleading as the error might have been caused by a different reason.
I suggest that we preserve the original error message to aid in debugging - something like the following:
```
            throw new ImperativeError({
                msg: `Failed to read namespace ${this.kubeConfig.namespace}: ${err}`,
            });
```

**Comment by traeok** [comment]
Here's what the error looks like in Zowe Explorer:

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/86500639/fd6f89af-cc83-4788-84ec-81356f4eb9f6)

I expected the error to occur, but with 3 errors in the message it might not be obvious to end-users as to why the credential manager failed to load.
